/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cn.com.taiji.learn;

import org.antlr.v4.runtime.CharStreams;
import org.antlr.v4.runtime.CommonTokenStream;
import org.antlr.v4.runtime.tree.ParseTree;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void arryInitTest()  {
        String source = "{1,2,3}";
        antlr.taiji.ArrayInitLexer lexer = new antlr.taiji.ArrayInitLexer(CharStreams.fromString(source)); // create a buffer of tokens pulled from the lexer
        CommonTokenStream tokens = new CommonTokenStream(lexer); // create a parser that feeds off the tokens buffer
        antlr.taiji.ArrayInitParser parser = new antlr.taiji.ArrayInitParser(tokens);
        ParseTree tree = parser.init(); // begin parsing at init rule
        System.out.println(tree.toStringTree(parser));
    }
}
